### ISSUE TITLE
Hello World example was broken

### ISSUE THREAD

**Issue by bkauler** [JulNadeauCA/libagar#10]
I posted this question on the "agar" mail-list, but there is no action there, so reposting here.

The libagar.org website has a Hello World example, `hello.c`. Testing with the Linux framebuffer, closing the window just resulted in a black screen, had to hold down the power button to reboot.

Here is the original hello.c:

```
#include <agar/core.h>
#include <agar/gui.h>
int main(int argc, char *argv) {
  AG_Window *win;
  if (AG_InitCore(NULL, 0) == -1 || AG_InitGraphics(0) == -1) {
    return (1);
  }
  win = AG_WindowNew(0);
  AG_LabelNew(win, 0, "Hello, world!");
  AG_WindowShow(win);
  AG_EventLoop();
  return (0);
}
```

After comparing with "agartest", I changed hello.c to this:

```
#include <agar/core.h>
#include <agar/gui.h>

int main(int argc, char *argv) {
  AG_Window *win;
  if (AG_InitCore(NULL, 0) == -1 || AG_InitGraphics(0) == -1) {
    return (1);
  }
  win = AG_WindowNew(AG_WINDOW_MAIN);
  AG_LabelNew(win, 0, "Hello, world!");
  AG_WindowShow(win);
  AG_EventLoop();
  AG_DestroyGraphics();
  AG_Destroy();
  return (0);
}
```

The most important is that flag `AG_WINDOW_MAIN`. I also put in `AG_DestroyGraphics()` and `AG_Destroy()`, as agartest has them, however they **ARE NOT DOCUMENTED**.

Now get a return to console prompt when close the window.

**Comment by JulNadeauCA** [comment]
Can you provide more details about the environment (Linux framebuffer)?

You will probably want to add to your code something like:

>  AG_BindStdGlobalKeys();

This binds common keys such as ESC -> AG_CloseFocusedWindow(), and Ctrl-Q -> AG_QuitGUI().

The AG_WINDOW_MAIN flag is now documented here:
http://libagar.org/man3/AG_Window#FLAGS

> Break from AG_EventLoop(3) if this window gets destroyed. Multiple windows may set this flag, in which case the break will occur whenever the last window is closed.
