### ISSUE TITLE
freetype-config is deprecated, should use pkg-config instead

### ISSUE THREAD

**Issue by heharkon** [JulNadeauCA/libagar#12]
The freetype-config tool is deprecated and configuration script should use pkg-config instead for detecting whether freetype library can be used. For example Ubuntu 19.04 has already dropped freetype-config from libfreetype6-dev package, so compiling libagar becomes impossible, without hacking the script.

**Comment by charlesdaniels** [comment]
Can confirm, I cannot build libagar 1.5.0 on Ubuntu 18.04 without `--without-freetype`.

**Comment by JulNadeauCA** [comment]
Can you guys check to see if the problem still persists with the latest sources from the repository?

The latest test should look for a "freetype2" pkg-config module first, before falling back to freetype-config if the pkg-config module is not found.

The source for the freetype configure test is at:
https://github.com/JulNadeauCA/BSDBuild/blob/master/BSDBuild/freetype.pm

**Comment by charlesdaniels** [comment]
Tested with 940f83bd42c5c2e9733229a4be875f5ed46e0b0f

Seems to be working.

Here is `conf.log` in case you want it:

[config.log](https://github.com/JulNadeauCA/libagar/files/3261878/config.log)

**Comment by heharkon** [comment]
Works for me too! Sorry, I should have tested with the latest revision before filing a bug. I just searched for the freetype-config text and didn't realize that it was just a fallback.

**Comment by heharkon** [comment]
Is not an issue with the latest revision.
