### ISSUE TITLE
segmentation fault when viewing surfaces in GUI debugger

### ISSUE THREAD

**Issue by charlesdaniels** [JulNadeauCA/libagar#14]
I am under the impression that 1.6 is going to make some changes, so this may not be applicable any longer. However, under 1.5 on Ubuntu 18.04, I get a segmentation fault when clicking the "Surfaces" tab, but only on certain window elements.

Here is the program I'm working on:

```c
/* Minimal application using Agar-GUI */

#include <agar/core.h>
#include <agar/gui.h>

void QuitApplication(AG_Event *event) {
	AG_Quit();
}

#ifdef ENABLE_DEBUGGER
void LaunchDebugger(AG_Event *event) {
	AG_Window* win;
	AG_Window* db_window;

	win = (AG_Window*) AG_ObjectRoot(AG_SELF());

	db_window = AG_GuiDebugger(win);
	AG_WindowShow(db_window);
}
#endif


int main(int argc, char *argv[]) {
	AG_Window *win;

	if (AG_InitCore(NULL, 0) == -1 ||
	    AG_InitGraphics(0) == -1)
		return (1);

	win = AG_WindowNew(0);
	AG_WindowSetCaptionS (win, "Graph Editor");

	AG_Menu* menu = AG_MenuNew(win, 0);
	AG_MenuItem* menu_file = AG_MenuNode(menu->root, "File", NULL);
	AG_MenuAction(menu_file, "Quit", NULL, QuitApplication, NULL);

#ifdef ENABLE_DEBUGGER
	AG_MenuAction(menu_file, "Launch Debugger", NULL, LaunchDebugger, NULL);
#endif

	AG_WindowShow(win);

	AG_EventLoop();
	return (0);
}

```

I am able to view the surfaces in say the `AG_MenuView #0` (under `glx3`), but viewing the surfaces for `glx1` produces a segfault. I have attached a log which includes both Agar's debug output, and a GDB backtrace.

[gdb.log](https://github.com/JulNadeauCA/libagar/files/3263066/gdb.log)

**Comment by JulNadeauCA** [comment]
This should no longer be happening with the latest updates to the GUI Debugger.  Feel free to re-open the issue if the problem still occurs with the latest SVN.
