### ISSUE TITLE
Error message "recipe for target 'depend' failed" when cross compiling for 32-bit windows  under MinGW

### ISSUE THREAD

**Issue by azaka** [JulNadeauCA/libagar#2]
$ ./configure --host=i686-w64-mingw32
$ make depend all
==> core
make[1]: Entering directory '/home/dell/libagar/libagar-master/core'
/mingw32/bin/gcc -M  -D_AGAR_INTERNAL -D_BSD_SOURCE -I/home/dell/libagar/libagar-master/include -D_AGAR_CORE_INTERNAL -D_XOPEN_SOURCE=600 -Ii686-w64-mingw32 time_win32.c time_posix.c time_renderer.c net.c net_dummy.c user_win32.c variable.c config.c core.c error.c event.c object.c prop.c timeout.c class.c cpuinfo.c data_source.c load_string.c load_version.c vsnprintf.c vasprintf.c asprintf.c dir.c md5.c sha1.c rmd160.c file.c string.c dso.c tree.c time.c time_dummy.c db.c tbl.c getopt.c exec.c text.c user.c user_dummy.c
dso.c:54:40: fatal error: dlfcn.h: No such file or directory
compilation terminated.
/mingw32/bin/gcc -M  -D_AGAR_INTERNAL -D_BSD_SOURCE -I/home/dell/libagar/libagar-master/include -D_AGAR_CORE_INTERNAL -D_XOPEN_SOURCE=600 -Ii686-w64-mingw32 time_win32.c time_posix.c time_renderer.c net.c net_dummy.c user_win32.c variable.c config.c core.c error.c event.c object.c prop.c timeout.c class.c cpuinfo.c data_source.c load_string.c load_version.c vsnprintf.c vasprintf.c asprintf.c dir.c md5.c sha1.c rmd160.c file.c string.c dso.c tree.c time.c time_dummy.c db.c tbl.c getopt.c exec.c text.c user.c user_dummy.c
dso.c:54:40: fatal error: dlfcn.h: No such file or directory
compilation terminated.
../mk/build.dep.mk:33: recipe for target 'depend' failed
make[1]: *** [depend] Error 1
make[1]: Leaving directory '/home/dell/libagar/libagar-master/core'
mk/build.subdir.mk:168: recipe for target 'depend-subdir' failed
make: *** [depend-subdir] Error 1

**Comment by JulNadeauCA** [comment]
This was fixed in svn (r9871). The fix will be included in the upcoming (1.5.1) release. Thanks,
