### ISSUE TITLE
Windows 10 libag_gui build error (MinGW-w64)

### ISSUE THREAD

**Issue by Brouilles** [JulNadeauCA/libagar#46]
Hi,
I follow this explanation https://libagar.org/docs/inst/win-mingw64.html but I have a problem. During `make install` I have the following warning:

```
libtool: install: `libag_gui.la' is not a valid libtool archive
libtool: install: Try `libtool --help --mode=install' for more information.
../mk/libtool/libtool --quiet --finish /usr/x86_64-w64-mingw32/sys-root/mingw/lib
install -c -m 644 style.css /usr/x86_64-w64-mingw32/sys-root/mingw/share/agar


*** Warning: linker path does not have real file for library -lag_gui.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libag_gui but no candidates were found. (...for file magic test)
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
```

And in the MinGW folder I don't have `libag_gui.a` (but I have others). And When I compiled the hello.c example, I get the following error: 

```
can't find -lag_gui
collect2: error: ld returned exit status 1
```

Because the .a file don't exist.
I using the last Cygwin64 version and Windows 10 (last version).
Any idea?

**Comment by JulNadeauCA** [comment]
Hi,

Could you try again with the development (SVN) sources?  The MinGW build process has changed in the 1.6 series.  We no longer use libtool at all, and our build system now handles building of DLLs by itself.

**Comment by Brouilles** [comment]
Hi,
Good news, it compile!
With the last version of the main branch on Github.

Just an error with this example code:
```
  #include <agar/core.h>
  #include <agar/gui.h>
  
  int
  main(int argc, char *argv)
  {
          AG_Window *win;
          
          if (AG_InitCore(NULL, AG_VERBOSE) == -1 ||
              AG_InitGraphics(0) == -1) {
		AG_Verbose("Init failed: %s\n", AG_GetError());
		return (1);
	  }
          win = AG_WindowNew(0);
          AG_LabelNew(win, 0, "Hello, world!");
          AG_WindowShow(win);
          AG_EventLoop();
          return (0);
  }
```
At startup, I have the following in console: `AG_FatalError: Packed RGB surfaces must be 8-, 16-, 24-, 32-, 48- or 64-bpp`. But I think the example is not up to date.

Also, I don't use 
```
x86_64-w64-mingw32-cc -o hello \
      `$MINGWROOT/bin/agar-config --cflags` hello.c \
      `$MINGWROOT/bin/agar-config --libs`
```
But `x86_64-w64-mingw32-gcc` because `x86_64-w64-mingw32-cc` is undefined.
Thanks!

**Comment by JulNadeauCA** [comment]
I'm glad to hear it!  The "Packed RGB surfaces ..." error is a bug unrelated to the example, which should have now been fixed as of r10701.

The installation guides have been updated to show x86_64-w64-mingw32-gcc instead of -cc. Thanks for pointing that out!
