### ISSUE TITLE
dyld: Symbol not found: _AG_GL_BackupSurfaces

### ISSUE THREAD

**Issue by TonalidadeHidrica** [JulNadeauCA/libagar#47]
I installed libagar into my Mac Mojave by the following steps, according to [the official guide](http://libagar.org/docs/inst/osx.html).

First, I installed SDL1.2 .  (I don't know it's needed though)

```console
$ brew install sdl
```

Next, I executed the following:

```console
$ tar -xzf agar-1.5.0.tar.gz
$ cd agar-1.5.0.tar.gz
$ ./configure --prefix=$HOME/lib/agar
$ make depend all
$ make install
```

Then I created a file named `hello.c` according to the bottom of the page.  I successfully compiled it, but when I try running, an dynamic library loading error occurs:
```console
$ cc -o hello (~/lib/agar/bin/agar-config --cflags | string split " ") hello.c (~/lib/agar/bin/agar-config --libs | string split " ")
$ ./hello
dyld: Symbol not found: _AG_GL_BackupSurfaces
  Referenced from: /Users/$USER/lib/agar//lib/libag_gui.5.dylib
  Expected in: flat namespace
 in /Users/$USER/lib/agar//lib/libag_gui.5.dylib
fish: './hello' terminated by signal SIGABRT (Abort)
```
(where `$USER` is actually the username of my PC.)

What am I getting wrong?  How can I fix this problem?

**Comment by TonalidadeHidrica** [comment]
A sloppy attempt of adding `DYLD_LIBRARY_PATH` also failed.

```
bash-3.2$ export DYLD_LIBRARY_PATH=/Users/seasellsheshell/lib/agar/bin/:/Users/seasellsheshell/lib/agar/share/
bash-3.2$ ./hello
dyld: Symbol not found: _AG_GL_BackupSurfaces
  Referenced from: /Users/seasellsheshell/lib/agar//lib/libag_gui.5.dylib
  Expected in: flat namespace
 in /Users/seasellsheshell/lib/agar//lib/libag_gui.5.dylib
Abort trap: 6
```

**Comment by JulNadeauCA** [comment]
Can you post the contents of config.log from the build directory? I suspect the test for OpenGL has failed for some reason, and your build is missing OpenGL support as a result.

Enabling SDL support adds support for the "sdlgl" and "sdlfb" drivers. This allows Agar applications to run in SDL/OpenGL or SDL/Framebuffer mode in addition to the native "cocoa" driver (which uses the Cocoa API). The "sdlgl" driver is also handy if you wish to provide a MDI or "single-window" mode in a multi-window application.

**Comment by JulNadeauCA** [comment]
Can you try again with version 1.6.0? (http://libagar.org/download.html) and please re-open the issue if the problem persists.
