### ISSUE TITLE
variable.c:26:10: fatal error: agar/core/core.h: No such file or directory

### ISSUE THREAD

**Issue by Sunchock** [JulNadeauCA/libagar#5]
$ make install
==> core
make[1] : on entre dans le répertoire « /usr/agar/core »
make[2] : on entre dans le répertoire « /usr/agar/core »
../mk/libtool/libtool --quiet --mode=compile \
    cc  -D_AGAR_CORE_INTERNAL         -o variable.lo -c variable.c
variable.c:26:10: fatal error: agar/core/core.h: No such file or directory
 #include <agar/core/core.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [../mk/build.lib.mk:110: variable.lo] Error 1
make[2] : on quitte le répertoire « /usr/agar/core »
make: failure
make[1]: *** [../mk/build.lib.mk:201: _lib_shobjs] Error 1
make[1] : on quitte le répertoire « /usr/agar/core »
make: *** [mk/build.subdir.mk:32: all-subdir] Error 1

> ?

**Comment by JulNadeauCA** [comment]
Has the ./configure script succeeded without error?
Can you post the contents of config.log?
