### ISSUE TITLE
SDL2 backend

### ISSUE THREAD

**Issue by gh-legacy** [JulNadeauCA/libagar#55]
Agar currently has SDL 1.2 backend. I think you choose it because SDL 1.2 is more portable than the new SDL2 but it's no longer to be the case. SDL2 now available from Windows to Linux, BSDs, SunOS and even HaikuOS. It's pretty stable now.

What do you think about a SDL2 backend?

**Comment by JulNadeauCA** [comment]
Yes, the addition of a standard SDL2 driver is definitely one of the top items planned for the upcoming 1.7 release (https://github.com/JulNadeauCA/libagar/blob/master/CHANGELOG.md#unreleased).

The code that needs to be ported is in [drv_sdl_common.c](/JulNadeauCA/libagar/tree/master/gui/drv_sdl_common.c), [drv_sdlfb.c](/JulNadeauCA/libagar/tree/master/gui/drv_sdlfb.c) and [drv_sdlgl.c](/JulNadeauCA/libagar/tree/master/gui/drv_sdlgl.c).  The main difference will be that SDL2 being multi-window, the SDL2 driver class will be derived from [AG_DriverMw](https://libagar.org/man3/AG_DriverMw) as opposed to [AG_DriverSw](https://libagar.org/man3/AG_DriverSw).
