### ISSUE TITLE
.../tests/configure is giving error 

### ISSUE THREAD

**Issue by sanliturk** [JulNadeauCA/libagar#6]
I have downloaded "master" and compiled it with the following statements :    

./configure --prefix=`pwd`/Installed
make -i -k depend all
make -i -k install

"Installed" directory has :  bin , include , lib , lib64 , local , share  directories .
Perhaps , during install , it deleted "lib64" , "local" directories , and created a "man" directory .

In  tools  directory  both 

./configure --prefix=`pwd`/Installed
./configure

statements gave errors .

In  tests directory 

[s@localhost tests]$ ./configure --prefix=`pwd`/../Installed
BSDBuild 3.2 <http://bsdbuild.hypertriton.com/>
checking for a C compiler...yes, /usr/bin/cc
checking whether the C compiler works...yes
cc: checking for compiler warning options...yes
cc: checking for long double...yes
cc: checking for long long...yes
cc: checking for cygwin environment...no
cc: checking for -mwindows option...no
cc: checking for -mconsole option...no
checking for Agar...no
* 
* This software requires agar installed on your system.
* It is available from: http://libagar.org
* 
configure failed!
[s@localhost tests]$ 

means  in ./configure  , --prefix has been ignored

Is there any possibility , please ,

(1) Combine "configure" statements into "configure" in "master" directory , and build sub directory parts with "make" options .

or 

(2) Correct the above errors .

If you download "master" into a machine which does not have any "libagar" related installations , you may reproduce the above problems .

"libagar"  1.5.0  downloaded from  http://libagar.org is also NOT buildable ...

OS : 
[s@localhost tests]$ uname -a
Linux localhost.localdomain 4.17.18-200.fc28.x86_64 #1 SMP Wed Aug 22 19:08:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[s@localhost tests]$ 

Fedora 28

Thank you very much for your contributions .

**Comment by JulNadeauCA** [comment]
Hi,

Could you post the contents of the config.log file that was generated in the ./tests directory after the "checking for Agar...no" message? It should contain the exact error that caused that test to fail.

The agartest test suite is not intended to be installed along with the library. It should be built (and packaged) separately. The utilities under ./tools are mostly useful for the maintainer and you don't need to worry about those.

**Comment by sanliturk** [comment]
[config.log.txt](https://github.com/JulNadeauCA/libagar/files/2612698/config.log.txt)

The ( renamed to *.txt to attach it here )  config.log file has been attached here . 
Terminal listing in /tests  is the following : 

[Read_Me_T_Test.txt](https://github.com/JulNadeauCA/libagar/files/2612700/Read_Me_T_Test.txt)

Terminal listing in "master"  is the following : 

[Read_Me_T_Make.txt](https://github.com/JulNadeauCA/libagar/files/2612701/Read_Me_T_Make.txt)


Terminal listing in "/tools"  is the following : 

[Read_Me_T_Tools.txt](https://github.com/JulNadeauCA/libagar/files/2612704/Read_Me_T_Tools.txt)

Thank you very much .


Mehmet Erol Sanliturk

**Comment by sanliturk** [comment]
The above files are from 2018_09_09 run .
Before uploading them , I did not checked presence  of new commits .
There are commits . I will try to recompile and upload the resultant listings .

config.log in /tests is the following : 

[config.log.txt](https://github.com/JulNadeauCA/libagar/files/2612709/config.log.txt)


Complete Terminal listing is the following ( There are some errors in some sources ) :  

[Read_Me_T.txt](https://github.com/JulNadeauCA/libagar/files/2612710/Read_Me_T.txt)



Thank you very much .

Mehmet Erol Sanliturk

**Comment by JulNadeauCA** [comment]
I believe the build errors you were seeing (that had to do with _Nullable and _Nonnull attributes) have been fixed. Please try again with current sources, and feel free to reopen the issue if the problem persists.
