### ISSUE TITLE
Incomplete certificate chain on libagar.org

### ISSUE THREAD

**Issue by AMDmi3** [JulNadeauCA/libagar#60]
FYI. This leads to failure to validate the certificate, such as:
```
% curl -I https://libagar.org 
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
See https://www.ssllabs.com/ssltest/analyze.html?d=libagar.org&latest for details

**Comment by JulNadeauCA** [comment]
The SSL certificate has been updated since. Thanks for the notice!

**Comment by GitMensch** [comment]
This happens again (server cert chain broken), see above URL, also see https://www.ssllabs.com/ssltest/analyze.html?d=stable.hypertriton.com which is - per libagar.org - the place for downloads.

workaround: download from `https://master.dl.sourceforge.net/project/agar/agar/${pkgver}/agar-${pkgver}.tar.gz`

Note: PGP key (per website) for the release tarballs is also expired.

**Comment by JulNadeauCA** [comment]
> This happens again (server cert chain broken), see above URL, also see https://www.ssllabs.com/ssltest/analyze.html?d=stable.hypertriton.com which is - per libagar.org - the place for downloads.
> 
> workaround: download from `https://master.dl.sourceforge.net/project/agar/agar/${pkgver}/agar-${pkgver}.tar.gz`

My mistake. Please try it again. The server should now return the complete certificate chain now.

> Note: PGP key (per website) for the release tarballs is also expired.

I will update the PGP key shortly. Thanks for the heads up!

**Comment by GitMensch** [comment]
curl does not report any errors any more, thanks for the fix!
Looking forward to update the MSYS2 package (definition now upstream, binary packages likely available tomorrow) including reverting to the right URL and likely reverting the perl quote patch once 1.7.2 is out.
