### ISSUE TITLE
Cygwin configuration script check is out of date.

### ISSUE THREAD

**Issue by WallyZambotti** [JulNadeauCA/libagar#62]
The following line taken from configure is used to determine if the environment is Cygwin:

echo "$CC $CFLAGS $TEST_CFLAGS -mcygwin -o $testdir/conftest$$ conftest$$.c 2>>config.log">>config.log

However the -mcygwin compiler flag is no longer supported and does not work.

So this test must fail resulting in compiles using cygwin using incorrect option settings for libtool (if used).

**Comment by WallyZambotti** [comment]
The uname utility under cygwin can be used to determine if the environment is cygwin.

**Comment by JulNadeauCA** [comment]
The configure scripts have been updated to no longer include the `-mcygwin` compiler flag. Thanks!
