### ISSUE TITLE
SG missing __APPLE__ directive in sg.h

### ISSUE THREAD

**Issue by WallyZambotti** [JulNadeauCA/libagar#64]
Line 13 of sg/sg.h

`# include <GL/glu.h>
`

should be changed to

```
#ifdef __APPLE__
# include <OpenGL/glu.h>
#else 
# include <GL/glu.h>
#endif

```
Otherwise fatal errors are caused when building in MacOS

**Comment by JulNadeauCA** [comment]
Fixed in r10939. Thanks!
