### ISSUE TITLE
last git version does not compile

### ISSUE THREAD

**Issue by scaramacai** [JulNadeauCA/libagar#7]
I'm testing new lib version, in particular up to commit 8e5a2e4a326b2e7cb56a839e57fec214a8b14667
At the very beginning of the compilation in the gui directory I receive the following messages:
**In file included from /tmp/libagar-master/include/agar/gui/widget.h:12,
                 from /tmp/libagar-master/include/agar/gui/window.h:6,
                 from drv_gl_common.c:32:
/tmp/libagar-master/include/agar/gui/surface.h:902:1: error: multiple storage classes in declaration specifiers
 extern DECLSPEC typedef AG_Surface AG_Anim;
 ^~~~~~
/tmp/libagar-master/include/agar/gui/surface.h:916:1: error: multiple storage classes in declaration specifiers
 extern DECLSPEC typedef AG_AlphaFn AG_BlendFn;
 ^~~~~~
drv_gl_common.c:849:35: error: expected ';', ',' or ')' before 'obj'
 AG_GL_DrawTriangle(void *_Nonnull obj, AG_Pt v1, AG_Pt v2, AG_Pt v3, AG_Color c)
                                   ^~~
make[2]: *** [../mk/build.lib.mk:135: drv_gl_common.o] Error 1
make[2]: Leaving directory '/tmp/libagar-master/gui'
make: failure
make[1]: *** [../mk/build.lib.mk:260: _lib_objs] Error 1
make[1]: Leaving directory '/tmp/libagar-master/gui'
make: *** [mk/build.subdir.mk:32: all-subdir] Error 1**

I'm on Linux Debian with gcc 8.2.0
Thank you.
Ciao.
Gigi

**Comment by scaramacai** [comment]
AG_GL_DrawTriangle(void _Nonnull obj, AG_Pt v1, AG_Pt v2, AG_Pt v3, AG_Color c)
should read AG_GL_DrawTriangle(void *_Nonnull obj, AG_Pt v1, AG_Pt v2, AG_Pt v3, AG_Color c)

**Comment by JulNadeauCA** [comment]
Hi,
Sorry about that, I was in the middle of making a large number of commits. It should be building correctly now. Could you try again with the latest revision?

**Comment by JulNadeauCA** [comment]
This is very helpful, thank you! Can you try revision 10050 and see if that fixes the problem?

Make sure to run ./configure again prior to rebuilding.

Most of these errors had to do with clang nullability specifiers on pthread types (pthread_t, pthread_mutex_t, etc). Because pthread types are pointers on some systems and not on others, I've had to add some configure tests to detect that. The typedef problem should be fixed as well.

**Comment by sanliturk** [comment]
This is my build listing generated now  in Fedora 28 .

[s@localhost ~]$ uname -a
Linux localhost.localdomain 4.18.18-200.fc28.x86_64 #1 SMP Mon Nov 12 03:17:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[s@localhost ~]$ 

There are errors .


[Read_Me_T.txt](https://github.com/JulNadeauCA/libagar/files/2616608/Read_Me_T.txt)

Mehmet Erol Sanliturk

**Comment by scaramacai** [comment]
Hi all,
I tried with trunk 10050 and 10052.
The typedef problem is fixed, but still I have problems with _Nonnull and _Nullable:

drv_glx.c:65:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'agDisplay'
 static Display  *_Nullable     agDisplay = NULL; /* X display handle */
                                ^~~~~~~~~
drv_glx.c:67:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'glxEventSink'
 AG_EventSink *_Nullable glxEventSink = NULL;  /* Process X events */
                         ^~~~~~~~~~~~
and so on, as well as
drv_glx.c:120:71: error: conflicting types for '_Nonnull'
 static void GLX_PostResizeCallback(AG_Window *_Nonnull, AG_SizeAlloc *_Nonnull);
                                                         ~~~~~~~~~~~~~~^~~~~~~~
drv_glx.c:120:47: note: previous definition of '_Nonnull' was here
 static void GLX_PostResizeCallback(AG_Window *_Nonnull, AG_SizeAlloc *_Nonnull);
                                    ~~~~~~~~~~~^~~~~~~~
etc.
In my opinion, since it seems that gcc cannot manage in a smart way something like _Nonnull or _Nullable (although it exists a nonnull attribute), _Nonnull and _Nullable could be `#undef` when gcc is used.
Anyway, in the meanwhile, I will install and try clang

Ciao.
Gigi

**Comment by scaramacai** [comment]
clang-7 works, but I'm not able to compile the test example with gcc (or at least configure says that
the libraries do not work with gcc)
Compiling the test by using clang is ok!
Could it be only a problem in configure? Are the libraries produced by clang supposed to work with gcc?

Ciao.
Gigi

**Comment by scaramacai** [comment]
clang-7 works, but I'm not able to compile the test example with gcc (or at least configure says that
the libraries do not work with gcc)
Compiling the test by using clang is ok!
Could it be only a problem in configure? Are the libraries produced by clang supposed to work with gcc?

Ciao.
Gigi

**Comment by scaramacai** [comment]
Since trunk 10061 (at least) both library and tests compile fine with gcc.
IHMO, as soon as git will be in sync with svn repo, this issue can be closed.
Ciao.
Gigi
