### ISSUE TITLE
Build error under macOS

### ISSUE THREAD

**Issue by kwhr0** [JulNadeauCA/libagar#77]
1. In `gui/drv_cocoa.m`, you need to remove the last argument of `AG_ProcessMouseMotion()`.

1. In `core/Makefile` and `gui/Makefile`, you need following line.

```
CFLAGS += -D_DARWIN_C_SOURCE
```

Without this, dirfd, u_int, etc. will be undefined.

**Comment by JulNadeauCA** [comment]
Thank you very much for reporting this!
Commits https://github.com/JulNadeauCA/libagar/commit/897fcdf5e2d9156bf03b449dcc420345115b29d1 and https://github.com/JulNadeauCA/libagar/commit/31503566ab6b61e0aa2ca04b0609e9ff1349e798 should fix the problem but I've only tested on MacOS X 10.5. If there's still a problem, please feel free to re-open the issue.
