### ISSUE TITLE
padding not working as expected in progress bar

### ISSUE THREAD

**Issue by scaramacai** [JulNadeauCA/libagar#81]
Tried the widget page of agartest, testing with negative and positive values of padding in my style sheet.  
I expected the whole progress bar be resized, but only the "external box" is, not the blue bar:

## Examples
I'm attaching some screenshots
### Agartest default
![Screenshot_2024-04-10_16-20-27_agar_progressbar_default](https://github.com/JulNadeauCA/libagar/assets/41902571/fd7df7be-5824-49e0-b247-4410e5e9c6ee)
### Negative value of padding
Note that percent value is not visible
![Screenshot_2024-04-10_16-20-27_agar_progressbar_my_style](https://github.com/JulNadeauCA/libagar/assets/41902571/de837b40-e167-440b-9a51-8bbff5d497f4)
### Positive "large" value of padding
![Screenshot_2024-04-10_21-30-17_agar_progress_bar_my_style_12](https://github.com/JulNadeauCA/libagar/assets/41902571/59605e3e-5bed-4e1c-b88e-39d3665d95ef)

**Comment by scaramacai** [comment]
I modified the progress bar code. Now it almost works, but I am not sure if the solution is the right one, because I have not studied AGAR's widget structure thoroughly. Also I still have some doubt that there may be  &plusmn; 1 px problems.

I attach the diff so that you can take a look at it.

```diff
--- progress_bar.c.orig
+++ progress_bar.c
@@ -230,58 +230,56 @@
 static void
 Draw(void *_Nonnull obj)
 {
        AG_ProgressBar *pb = obj;
        AG_Rect rd = WIDGET(pb)->r;
        const int paddingLeft   = WIDGET(pb)->paddingLeft;
        const int paddingRight  = WIDGET(pb)->paddingRight;
        const int paddingTop    = WIDGET(pb)->paddingTop;
        const int paddingBottom = WIDGET(pb)->paddingBottom;
        int min, max, val;
 
        min = AG_GetInt(pb, "min");
        max = AG_GetInt(pb, "max");
        val = AG_GetInt(pb, "value");
        if (val < min) { val = min; }
        if (val > max) { val = max; }
 
        AG_DrawBoxSunk(pb, &rd, &WCOLOR(pb,BG_COLOR));
 
        if ((max - min) <= 0)
                return;
 
-       rd.x = paddingLeft;
-       rd.y = paddingTop;
+       rd.x = 0;
+       rd.y = 0;
 
        switch (pb->type) {
        case AG_PROGRESS_BAR_VERT:
-               rd.h -= (paddingTop + paddingBottom);
-               rd.y += rd.h - (val-min)*(rd.h)/(max-min) - 1;
-               rd.h = HEIGHT(pb) - paddingTop - rd.y + 1;
-               rd.w -= (paddingLeft + paddingRight);
+                rd.y += rd.h - (val-min)*(rd.h)/(max-min) - 1;
+                rd.h = HEIGHT(pb) - rd.y;
+               rd.w -= 1;
                break;
        case AG_PROGRESS_BAR_HORIZ:
        default:
-               rd.w = (val-min)*(rd.w - paddingLeft - paddingRight)/(max-min);
-               rd.h -= (paddingTop + paddingBottom);
+               rd.w = (val-min)*(rd.w - 1)/(max-min);
                break;
        }
        AG_DrawRect(pb, &rd, &WCOLOR(pb,SELECTION_COLOR));
 
        if (pb->flags & AG_PROGRESS_BAR_SHOW_PCT)
                DrawPercentText(pb);
 }
 
 AG_WidgetClass agProgressBarClass = {
        {
                "Agar(Widget:ProgressBar)",
                sizeof(AG_ProgressBar),
                { 1,0, AGC_PROGRESSBAR, 0xE032 },
                Init,
                NULL,           /* reset */
                Destroy,
                NULL,           /* load */
                NULL,           /* save */
                NULL            /* edit */
        },
        Draw,
        SizeRequest,
```

If you think I should submit a push request I will try to clone the repository and do it.

**Comment by JulNadeauCA** [comment]
Looks good to me! Committed to: https://github.com/JulNadeauCA/libagar/commit/1140aa6aeb3b99ce76c890fe1fdd817bc7763801. Thank you very much!
